#!/bin/bash
echo "Correcting filesystem permissions..."

./cli chown -R app:app /var/www

./cli find var vendor pub/static pub/media app/etc -type f -exec chmod u+w {} \;
./cli find var vendor pub/static pub/media app/etc -type d -exec chmod u+w {} \;
./cli chmod u+x bin/magento

echo "Filesystem permissions corrected."
